stages:
  - .pre
  - build
  - deploy

workflow:
  rules:
    # commit or merge
    - if: $CI_COMMIT_BRANCH
    # tag
    - if: $CI_COMMIT_TAG =~ /^\d{1,3}\.\d{1,3}\.\d{1,3}(-rc[1-9]\d?)?$/

###      PRE       ###
"Version":
  stage: .pre
  tags:
    - "init"
  environment: INT
  image: "bash:5.2"
  before_script:
    - apk add curl jq
  script:
    - source ci/lib-release.sh
    - set -x # Activate debug.
    - '[[ -z "${CI_COMMIT_BRANCH}" ]] || create_build_number_version_env'
    - '[[ -z "${CI_COMMIT_TAG}" ]] || create_tag_version_env'
  artifacts:
    reports:
      dotenv: "variables.env"
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH =~ /^release(\/.+)?$/
    - if: $CI_COMMIT_BRANCH =~ /^devops\/.*$/
    - if: $CI_COMMIT_TAG =~ /^\d{1,3}\.\d{1,3}\.\d{1,3}(-rc[1-9]\d?)?$/

###     BUILD       ###
"Build Image":
  stage: build
  tags:
    - "build"
  environment: INT
  image: "docker:stable"
  needs:
    - "Version"
  before_script:
    - apk add --update bash curl jq
  script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - bash -xc "source ./ci/lib-build.sh; docker_build_image CMS_VERSION=${VERSION}"
    - bash -xc "source ./ci/lib-build.sh; docker_push_image"
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH =~ /^release(\/.+)?$/
    - if: $CI_COMMIT_BRANCH =~ /^devops\/.*$/
    - if: $CI_COMMIT_TAG =~ /^\d{1,3}\.\d{1,3}\.\d{1,3}(-rc[1-9]\d?)?$/

###     DEPLOY      ###
"Deploy CMS":
  stage: deploy
  tags:
    - "deploy"
  image: "kroniak/ssh-client:3.15"
  needs:
    - "Version"
    - "Build Image"
  environment: INT
  variables:
    SSH_CONNECT: "deploy@portal.kav.skit.zone"
  before_script:
    - apk add --update bash curl jq
  script:
    - source ./ci/lib-deploy.sh
    - set -x # Activate debug.
    - deploy_docker_compose
    - check_url "https://cms.kav.skit.zone/health" 30 30 200
    - set_cron "*/30 * * * *" "/usr/bin/docker image prune -af > /dev/null"
    - set_cron "*/10 * * * *" "docker exec cms-kav-slovensko ./vendor/bin/drush cron >> /srv/cms_cron.log 2>&1"
    - set_cron "* * * * *" "docker exec cms-kav-slovensko ./vendor/bin/drush scheduler:cron >> /srv/cms_cron.log 2>&1"
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_TAG =~ /^\d{1,3}\.\d{1,3}\.\d{1,3}(-rc[1-9]\d?)?$/
